name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ianmgg/php74:latest
    - name: Push :latest
      run: docker push ianmgg/php74:latest
    - name: Build the dev Docker image
      run: docker build . --file Dockerfile.dev --tag ianmgg/php74:dev
    - name: Push :dev
      run: docker push ianmgg/php74:dev
